### ISSUE TITLE
version numbering

### ISSUE THREAD

**Issue by gabi2** [libyui/libyui-ncurses#17]
I want to create an 12.3 update for libyui-ncurses and have created the branch openSUSE-12_3 based on 2.43.3 (version on 12.3). Version numbering in master was continued to 2.43.4/5/ etc. This means I have to create 2.43.3.1 for the update. How is this done?
I think the MINOR number in libyui-ncurses master should have been increased from 43 to 44 for 13.1. development. We should do it now. 
AFAICS libyui-qt has increased MINOR number after 12.3 from 42 to 43.
For me it doesn't make sense to have different MINOR numbers for libyui-qt (43) and libyui-nurses (44) on same distribution. How to solve this problem?

**Comment by ancorgs** [comment]
The build system was fully revamped recently. That includes the way in which we will tag and version libyui in the future.

Closing this issue.
