### ISSUE TITLE
YTreeItem, only fisrt item is selected.

### ISSUE THREAD

**Issue by anaselli** [libyui/libyui-ncurses#26]
@mvidner and @gabi2 it seems that a patch i provided time ago has been reverted, i don't say it's wrong, but in any case now YTree item selection at creating time does not work any more.  See also https://github.com/libyui/libyui/pull/74

**Comment by mvidner** [comment]
[bnc#866145](https://bugzilla.suse.com/show_bug.cgi?id=866145) basically says:

> I'm trying to edit the partition setup in YaST.  When I select "Finish", YaST dies with:
...
 Error: signal 11
 [bt]: (3) /usr/lib64/libstdc++.so.6 : __dynamic_cast+0x7c [0x3fffd005684]
 [bt]: (4) /usr/lib64/yui/libyui-ncurses.so.6 : 
           NCTree::getCurrentItem() const+0x58 [0x3fffc1b47e0]

And then
> Segfault is fixed in libyui-ncurses6-2.46.3.

BTW the commit that fixes the bug, 6e776640c76bea2b9bda7533063653b793854a36, is not exactly a revert of the original commit, 55cc3a310881765c3af1fa859118a7ac6d031364.

**Comment by mvidner** [comment]
#50 merged and released as libyui-ncurses-2.47.7
