### ISSUE TITLE
Ambiguous versioning

### ISSUE THREAD

**Issue by sashko** [libyui/libyui-ncurses#94]
I see that version has been bumped to `2.55.0` recently, but the latest version tag is `2.52.0`.

Could you please clarify whether there are newer official releases and create appropriate tags, so package maintainers know what to use.

**Comment by shundhammer** [comment]
This is now in the new unified https://github.com/libyui/libyui repo which uses the same version number for all the subprojects.

We are working on bringing version tagging back to life.
